---
name: Batch Docker
description: Build and upload a directory full of docker contexts easily
inputs:
  root-directory:
    description: The root directory that contains each of the image directories
    required: true
  changed-files:
    description: A list of files that have changed since the last workflow run
    required: true
  project:
    description: GCP project that contains the intended GCR target
runs:
  using: node12
  main: dist/main.js
