---
name: Batch Docker
description: Build and upload a directory full of docker contexts easily
inputs:
  root-directory:
    description: The root directory that contains each of the image directories
    required: true
  changed-files:
    description: A list of files that have changed since the last workflow run
    required: true
  registry:
    description: The prefix for the Docker registry to push to
    required: true
runs:
  using: node12
  main: dist/main.js
