---
name: Test

'on': push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Run colpal/actions-batch-docker
        uses: ./
        with:
          root-directory: test/images
          changed-files: |
            [
              "test/images/image-1/Dockerfile.image-1",
              "test/images/image-2/Dockerfile.image-2",
              "test/unrelated.txt"
            ]
          project: cp-sandbox-nicholas-farl671
