---
name: Test

'on': push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - id: changed
        uses: colpal/actions-changed-files@v1.0.0
      - name: Run colpal/actions-populate-dagbag
        uses: ./
        with:
          root-directory: test/dags
          changed-files: ${{ steps.changed.outputs.json }}
          project: cp-sandbox-nicholas-farl671
