---
name: Test

'on': push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - id: changed
        uses: colpal/actions-changed-files@v1.0.0
      - name: Run colpal/actions-populate-dagbag
        uses: ./
        with:
          root-directory: test/dags
          changed-files: '["test/dags/dag-1/Dockerfile.dag-1","test/dags/dag-2/Dockerfile.dag-2","test/unrelated.txt"]'
          project: cp-sandbox-nicholas-farl671
